import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import vm from 'node:vm';
const context=vm.createContext({crypto:globalThis.crypto,Date,console});
vm.runInContext(readFileSync(new URL('../integrations/apps-script/Core.gs',import.meta.url),'utf8'),context);
const {emptyWorkspace,applyAction,day}=context.SolarCore;
const now='2026-09-06T10:00:00Z';let n=0;
const run=(state,type,payload={},at=now,request_id='test-'+(++n))=>applyAction(state,{type,payload,request_id},'Test operator',at);
function seed(){let s=emptyWorkspace();s.team=[{team_member:'Sales',role:'Sales Executive',project_type_supported:'Commercial',active_status:'Active'},{team_member:'Engineer',role:'Site Engineer',project_type_supported:'Commercial',active_status:'Active'}];return run(s,'create_lead',{client_name:'Demo User',email:'DEMO@example.com',location:'Delhi',project_type:'Commercial',lead_key:'FORM|one|demo@example.com|',estimated_capacity:'Not sure',timeline:'Within 1 month'}).state;}
function claim(s,kind='email'){s.config.AUTOMATION_ENABLED='Yes';s.config.TEST_RECEIVER_EMAIL='test@example.com';s.config.TEST_CALENDAR_ID='test-calendar';let o=run(s,'claim_delivery',{kind});return {state:o.state,task:o.result.task};}
function begin(s,t){return run(s,'begin_delivery',{delivery_id:t.delivery_id,claim_token:t.claim_token});}
test('IST date remains correct across UTC midnight',()=>{assert.equal(day('2026-09-06T20:00:00Z'),'2026-09-07');assert.equal(day('2026-09-06T02:00:00Z'),'2026-09-06');});
test('intake persists lead, intelligence, manual task and queued acknowledgement together',()=>{const s=seed();assert.equal(s.leads.length,1);assert.equal(s.intelligence.length,1);assert.equal(s.followups.length,1);assert.equal(s.deliveries.length,1);assert.equal(s.leads[0].assigned_to,'Sales');assert.equal(s.followups[0].automation_enabled,'No');assert.equal(s.intelligence[0].ai_used,'No');assert.match(s.intelligence[0].missing_information,/capacity/i);});
test('duplicate form key cannot create another lead or message',()=>{const s=seed(),o=run(s,'create_lead',{lead_key:s.leads[0].lead_key});assert.equal(o.state.leads.length,1);assert.equal(o.state.deliveries.length,1);assert.equal(o.result.duplicate,true);});
test('same request replay leaves version and state unchanged',()=>{const s=seed();const a={type:'add_followup',request_id:'stable',payload:{lead_id:s.leads[0].lead_id,due_date:'2026-09-07'}};const first=applyAction(s,a,'Test',now),second=applyAction(first.state,a,'Test',now);assert.equal(second.state.version,first.state.version);assert.equal(second.state.followups.length,2);});
test('invalid dates and email fail before any partial state can escape',()=>{const s=seed();assert.throws(()=>run(s,'add_followup',{lead_id:s.leads[0].lead_id,due_date:'2026-02-31'}),/valid date/);assert.equal(s.followups.length,1);});
test('paused workers do not consume activity rows or update the revision',()=>{const s=seed(),o=run(s,'claim_delivery',{kind:'email'});assert.equal(o.result.task,null);assert.equal(o.state.version,s.version);assert.equal(o.state.activity.length,s.activity.length);});
test('TEST delivery uses only configured test inbox',()=>{const c=claim(seed()),o=begin(c.state,c.task);assert.equal(o.result.task.payload.to,'test@example.com');assert.equal(o.state.deliveries[0].status,'Sending');});
test('blank test recipient cannot start delivery',()=>{const c=claim(seed());c.state.config.TEST_RECEIVER_EMAIL='';assert.throws(()=>begin(c.state,c.task),/Email/);assert.equal(c.state.deliveries[0].status,'Claimed');});
test('stop between claim and begin prevents sending and closes pending tasks',()=>{const c=claim(seed()),s=run(c.state,'update_lead',{lead_id:c.state.leads[0].lead_id,manual_stop:'Yes'}).state;assert.throws(()=>begin(s,c.task),/claim/);assert.equal(s.followups[0].followup_status,'Stopped');assert.equal(s.deliveries[0].status,'Cancelled');});
test('only due, opted-in email tasks are queued, once each',()=>{let s=seed();s.config.AUTOMATION_ENABLED='Yes';s=run(s,'add_followup',{lead_id:s.leads[0].lead_id,due_date:'2026-09-06',channel:'Email',automation_enabled:'Yes'}).state;s=run(s,'queue_followups').state;assert.equal(s.deliveries.length,2);assert.equal(run(s,'queue_followups').state.deliveries.length,2);});
test('manual completion cancels queued follow-up and sets next date',()=>{let s=seed();s.config.AUTOMATION_ENABLED='Yes';s=run(s,'add_followup',{lead_id:s.leads[0].lead_id,due_date:'2026-09-06',channel:'Email',automation_enabled:'Yes'}).state;s=run(s,'queue_followups').state;const f=s.followups[1];s=run(s,'complete_followup',{followup_id:f.followup_id,outcome:'Contacted',next_due_date:'2026-09-08'}).state;assert.equal(s.deliveries.find(d=>d.source_id===f.followup_id).status,'Cancelled');assert.equal(s.followups[1].followup_status,'Completed');assert.equal(s.leads[0].next_followup_date,'2026-09-08');});
test('turned-off individual task is checked again immediately before sending',()=>{let s=seed();s.deliveries=[];s.config.AUTOMATION_ENABLED='Yes';s=run(s,'add_followup',{lead_id:s.leads[0].lead_id,due_date:'2026-09-06',channel:'Email',automation_enabled:'Yes'}).state;s=run(s,'queue_followups').state;const c=claim(s);c.state.followups[1].automation_enabled='No';const o=begin(c.state,c.task);assert.equal(o.result.task,null);assert.equal(o.state.deliveries[0].status,'Cancelled');});
test('uncertain Sending tasks are never automatically retried',()=>{const c=claim(seed()),b=begin(c.state,c.task);const o=run(b.state,'claim_delivery',{kind:'email'},'2026-09-06T10:16:00Z');assert.equal(o.result.task,null);assert.equal(o.state.deliveries[0].status,'Needs review');});
test('a stale pre-send claim can be reclaimed',()=>{const c=claim(seed());const o=run(c.state,'claim_delivery',{kind:'email'},'2026-09-06T10:16:00Z');assert.ok(o.result.task);assert.notEqual(o.result.task.claim_token,c.task.claim_token);});
test('manual reconciliation records a confirmed send without resending',()=>{const c=claim(seed()),b=begin(c.state,c.task);let s=run(b.state,'finish_delivery',{delivery_id:c.task.delivery_id,claim_token:c.task.claim_token,ok:false,error_message:'timeout'}).state;s=run(s,'reconcile_delivery',{delivery_id:c.task.delivery_id,resolution:'sent',provider_id:'gmail-123',note:'Verified in Gmail Sent'}).state;assert.equal(s.deliveries[0].status,'Sent');assert.ok(s.leads[0].acknowledgement_sent_at);});
test('proposal revisions cancel old queued documents and prevent old attachments',()=>{let s=seed();s=run(s,'create_proposal',{lead_id:s.leads[0].lead_id,amount:100000,notes:'First scope'}).state;const id=s.proposals[0].proposal_id;s=run(s,'update_proposal',{proposal_id:id,operation:'revise',amount:120000,notes:'Revised scope'}).state;assert.equal(s.proposals[0].proposal_version,2);assert.equal(s.deliveries.filter(d=>d.kind==='document'&&d.status==='Pending').length,1);assert.equal(s.deliveries.filter(d=>d.kind==='document'&&d.status==='Cancelled').length,1);assert.throws(()=>run(s,'update_proposal',{proposal_id:id,operation:'share'}),/Generate/);});
test('proposal cannot be accepted before delivery confirmation',()=>{let s=seed();s=run(s,'create_proposal',{lead_id:s.leads[0].lead_id,amount:100000,notes:'Scope'}).state;assert.throws(()=>run(s,'update_proposal',{proposal_id:s.proposals[0].proposal_id,operation:'accept'}),/Share/);});
test('completed visits require findings and retain the IST schedule',()=>{let s=seed();s=run(s,'schedule_visit',{lead_id:s.leads[0].lead_id,assigned_engineer:'Engineer',starts_at:'2026-09-07T10:00:00+05:30'}).state;assert.equal(s.visits[0].visit_date,'2026-09-07');assert.throws(()=>run(s,'update_visit',{site_visit_id:s.visits[0].site_visit_id,visit_status:'Completed'}),/findings/);});
test('all generated imports have valid topology and no active schedules or credentials',()=>{const dir=new URL('../integrations/n8n/',import.meta.url);const files=readdirSync(dir).filter(x=>x.endsWith('.json'));assert.equal(files.length,6);for(const file of files){const w=JSON.parse(readFileSync(new URL(file,dir),'utf8')),names=new Set(w.nodes.map(n=>n.name));assert.equal(w.active,false);assert.equal(names.size,w.nodes.length);for(const node of w.nodes){assert.equal(node.credentials,undefined);if(node.type==='n8n-nodes-base.code')new Function(node.parameters.jsCode);if(node.parameters.jsonBody)new Function('return '+node.parameters.jsonBody.slice(3,-3));}for(const [from,outputs] of Object.entries(w.connections)){assert.ok(names.has(from));for(const a of outputs.main)for(const edge of a)assert.ok(names.has(edge.node));}}});
test('form normalization handles every row with its own item pairing',()=>{const w=JSON.parse(readFileSync(new URL('../integrations/n8n/01_enquiry_intake.json',import.meta.url),'utf8'));const js=w.nodes.find(n=>n.name==='Normalize enquiries').parameters.jsCode;const rows=[1,2].map(i=>({json:{Timestamp:'06/09/2026 14:00:0'+i,'Client Name':'Demo '+i,Email:'DEMO'+i+'@example.com',Phone:'98 765 '+i,Location:'Delhi','Project Type':'Commercial',use_ai:false}}));const result=new Function('$input',js)({all:()=>rows});assert.equal(result.length,2);assert.notEqual(result[0].json.enquiry.lead_key,result[1].json.enquiry.lead_key);assert.equal(result[1].pairedItem.item,1);assert.equal(result[1].json.enquiry.email,'demo2@example.com');});
test('Apps Script adapter parses independently without unsupported module imports',()=>{new vm.Script(readFileSync(new URL('../integrations/apps-script/Bridge.gs',import.meta.url),'utf8'));assert.ok(!readFileSync(new URL('../integrations/apps-script/Core.gs',import.meta.url),'utf8').includes('cloudflare:workers'));});

test('pausing globally after a claim retains the task for later',()=>{const c=claim(seed());c.state.config.AUTOMATION_ENABLED='No';const o=begin(c.state,c.task);assert.equal(o.result.task,null);assert.equal(o.state.deliveries[0].status,'Pending');});
