'use client';

import {useEffect,useRef,useState,type FormEvent} from 'react';
import {Bot,BookOpen,CheckCircle2,ChevronRight,Database,LockKeyhole,Send,ShieldCheck,Sparkles,Wrench} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {Message,MessageContent,MessageResponse} from '@/components/ai-elements/message';
import {SOLAR_KNOWLEDGE} from '@/lib/solar-knowledge';

type Trace={tool:string;summary:string;sources:string[];duration_ms:number;status:'complete'|'error'};
type ActivityRecord={id:string;created_at:string;question:string;provider:string;model:string;tool_count:number;tools:string[];sources:string[];status:'complete'|'error'};
type ChatMessage={id:string;role:'user'|'assistant';content:string;traces?:Trace[];provider?:string;model?:string};
const ACTIVITY_KEY='solarops-agent-activity-v1';
const suggestions=["What is happening with Rajesh Sharma's solar project?","Which projects are delayed?","Why hasn't Priya Kapoor's installation moved forward?","Which customers need follow-up today?","What should happen after a site survey?","Show projects waiting for proposals."];

function readActivity():ActivityRecord[]{try{return JSON.parse(localStorage.getItem(ACTIVITY_KEY)||'[]') as ActivityRecord[]}catch{return []}}
function storeActivity(record:ActivityRecord){const next=[record,...readActivity()].slice(0,50);localStorage.setItem(ACTIVITY_KEY,JSON.stringify(next));window.dispatchEvent(new Event('solarops-activity'));}

export function SolarOpsAIPanel(){
 const [messages,setMessages]=useState<ChatMessage[]>([{id:'intro',role:'assistant',content:'I’m **SolarOps AI**, a read-only operations assistant. I can inspect synthetic customer and project records, identify delays, retrieve survey/proposal/task details, and use the Solar SOP library.\n\nI can recommend a next action, but I cannot execute it.'}]);
 const [question,setQuestion]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const endRef=useRef<HTMLDivElement>(null);const latest=[...messages].reverse().find(x=>x.traces?.length);
 useEffect(()=>{endRef.current?.scrollIntoView({behavior:'smooth',block:'nearest'})},[messages,busy]);
 async function ask(raw?:string){const value=(raw??question).trim();if(!value||busy)return;const user:ChatMessage={id:crypto.randomUUID(),role:'user',content:value};setMessages(x=>[...x,user]);setQuestion('');setError('');setBusy(true);
  try{const response=await fetch('/api/agent',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:value})});const data=await response.json() as {answer?:string;traces?:Trace[];sources?:string[];provider?:{name:string;model:string;configured:boolean};activity?:{id:string;created_at:string;tool_count:number};error?:string};if(!response.ok||!data.answer)throw new Error(data.error||'SolarOps AI returned an incomplete answer.');
   const assistant:ChatMessage={id:data.activity?.id||crypto.randomUUID(),role:'assistant',content:data.answer,traces:data.traces||[],provider:data.provider?.name,model:data.provider?.model};setMessages(x=>[...x,assistant]);storeActivity({id:assistant.id,created_at:data.activity?.created_at||new Date().toISOString(),question:value,provider:data.provider?.name||'Unknown',model:data.provider?.model||'Unknown',tool_count:data.activity?.tool_count||data.traces?.length||0,tools:(data.traces||[]).map(x=>x.tool),sources:data.sources||[],status:'complete'});
  }catch(e){const message=e instanceof Error?e.message:'SolarOps AI is unavailable.';setError(message);storeActivity({id:crypto.randomUUID(),created_at:new Date().toISOString(),question:value,provider:'Unavailable',model:'—',tool_count:0,tools:[],sources:[],status:'error'});}finally{setBusy(false)}}
 function submit(e:FormEvent){e.preventDefault();void ask();}
 return <div className="solarops-layout"><section className="panel solarops-chat"><div className="solarops-chat-head"><div className="agent-avatar"><Bot/></div><div><h2>SolarOps AI</h2><p>Grounded operational answers · read-only</p></div><span className="readonly-pill"><LockKeyhole size={13}/>Actions disabled</span></div>
  <div className="solarops-messages" aria-live="polite">{messages.map(message=><Message from={message.role} key={message.id}><MessageContent className={message.role==='assistant'?'agent-message':'user-message'}>{message.role==='assistant'?<MessageResponse>{message.content}</MessageResponse>:message.content}{message.role==='assistant'&&message.provider&&<small className="answer-provider">{message.provider} · {message.model}</small>}</MessageContent></Message>)}{busy&&<Message from="assistant"><MessageContent className="agent-message"><span className="thinking"><Sparkles size={15}/>Checking project records and SOP guidance…</span></MessageContent></Message>}<div ref={endRef}/></div>
  {messages.length===1&&<div className="prompt-grid">{suggestions.map(x=><button key={x} onClick={()=>void ask(x)}><span>{x}</span><ChevronRight size={15}/></button>)}</div>}
  {error&&<div className="agent-error" role="alert">{error}</div>}
  <form className="agent-composer" onSubmit={submit}><Textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask about a customer, project status, delay, task, proposal, survey, or SOP…" maxLength={600} rows={3} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void ask();}}}/><div><span>{question.length}/600 · Enter to send</span><Button className="primary-button" type="submit" disabled={busy||!question.trim()}><Send size={16}/>Ask SolarOps</Button></div></form></section>
  <aside className="solarops-side"><section className="panel trace-panel"><div className="panel-heading"><div><h2>Agent activity</h2><p>Safe tool visibility, not chain-of-thought.</p></div><ShieldCheck size={19}/></div>{latest?.traces?.length?<div className="trace-list">{latest.traces.map((trace,i)=><article key={`${trace.tool}-${i}`}><span><Wrench size={14}/></span><div><strong>{trace.tool.replaceAll('_',' ')}</strong><p>{trace.summary}</p><small>{trace.sources.join(' · ')} · {trace.duration_ms} ms</small></div><CheckCircle2 size={15}/></article>)}</div>:<div className="trace-empty"><Database size={22}/><p>Ask a question to see which read-only tools and sources were used.</p></div>}</section>
  <section className="panel guardrail-card"><h3><LockKeyhole size={16}/>Read-only guardrails</h3><p>No n8n actions, customer contact, scheduling, record updates, or approvals can run from this agent.</p><strong>Recommendations are never executions.</strong></section></aside></div>;
}

export function KnowledgePanel(){return <div className="knowledge-grid">{SOLAR_KNOWLEDGE.map(doc=><article className="panel knowledge-card" key={doc.id}><div><span><BookOpen size={18}/></span><small>{doc.category}</small></div><h2>{doc.title}</h2><p>{doc.summary}</p><details><summary>View synthetic guidance</summary><p>{doc.content}</p></details><footer>Reviewed {new Date(doc.reviewed+'T12:00:00Z').toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}</footer></article>)}</div>}

export function AgentActivityPanel(){const [records,setRecords]=useState<ActivityRecord[]>([]);useEffect(()=>{const sync=()=>setRecords(readActivity());sync();window.addEventListener('solarops-activity',sync);return()=>window.removeEventListener('solarops-activity',sync)},[]);return <section className="panel agent-activity-panel"><div className="panel-heading"><div><h2>Agent Activity</h2><p>Safe metadata recorded in this browser. Prompts, tools, sources, and outcomes only.</p></div><span>{records.length} runs</span></div>{records.length?<div className="agent-run-list">{records.map(record=><article key={record.id}><span className={record.status==='complete'?'run-ok':'run-error'}>{record.status==='complete'?<CheckCircle2/>:<Bot/>}</span><div><strong>{record.question}</strong><p>{record.tools.length?record.tools.join(' · '):'No tool completed'} </p><small>{record.provider} · {record.model} · {record.sources.join(', ')||'No sources'}</small></div><time>{new Date(record.created_at).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}</time></article>)}</div>:<div className="trace-empty"><Bot size={25}/><p>No agent runs have been recorded in this browser yet.</p></div>}</section>}
