'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {Sun,LayoutDashboard,Users,Clock3,MapPin,FileText,Activity,Settings2,Plus,ArrowUpRight,Search,RefreshCw,Check,PauseCircle,Play,AlertCircle,ChevronRight,Download,CalendarDays} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarGroup,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarInset,SidebarTrigger} from '@/components/ui/sidebar';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Skeleton} from '@/components/ui/skeleton';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {day,addDays,isStopped,type Workspace,type Row} from '@/lib/solar-core';
const nav=[['overview','Overview',LayoutDashboard],['leads','Enquiries',Users],['followups','Follow-ups',Clock3],['visits','Site visits',MapPin],['proposals','Proposals',FileText],['activity','Activity',Activity],['setup','Connections',Settings2]] as const;
const date=(v:any)=>v?new Date(/^\d{4}-\d{2}-\d{2}$/.test(v)?v+'T12:00:00+05:30':v).toLocaleDateString('en-IN',{day:'numeric',month:'short',timeZone:'Asia/Kolkata'}):'—';
const money=(v:any)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(v||0));
const badgeClass=(v:any)=>/hot|overdue|review|lost|declined/i.test(v)?'red':/completed|accepted|converted|sent|synced|ready/i.test(v)?'green':/warm|pending|draft|queued|scheduled/i.test(v)?'amber':'blue';
function Badge({children}:{children:any}){return <span className={'badge '+badgeClass(children)}>{children||'New'}</span>}
function Choice({name,options,value,onChange,label}:{name?:string;options:string[];value?:string;onChange?:(v:string)=>void;label?:string}){return <Select name={name} {...(onChange?{value:value||options[0],onValueChange:onChange}:{defaultValue:value||options[0]})}><SelectTrigger aria-label={label||name}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o} value={o}>{o}</SelectItem>)}</SelectContent></Select>}
function Field({name,label,value='',type='text',required=false}:{name:string;label:string;value?:any;type?:string;required?:boolean}){return <label className="field"><span>{label}</span><Input name={name} type={type} defaultValue={value} required={required} min={type==='number'?'1':undefined}/></label>}
function Empty({text}:{text:string}){return <div className="empty"><Sun size={30}/><p>{text}</p></div>}
export default function WorkspaceApp(){
 const [state,setState]=useState<Workspace|null>(null),[mode,setMode]=useState('demo'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[view,setView]=useState('overview'),[query,setQuery]=useState(''),[filter,setFilter]=useState('All'),[selected,setSelected]=useState<string|null>(null),[modal,setModal]=useState<Row|null>(null);
 async function load(){setError('');try{const r=await fetch('/api/workspace');const d=await r.json() as {state?:Workspace;mode?:string;error?:string};if(!r.ok||!d.state||!d.mode)throw new Error(d.error||'The workspace response was incomplete.');setState(d.state);setMode(d.mode);}catch(e){setError(e instanceof Error?e.message:'Unable to load workspace.');}}
 useEffect(()=>{load()},[]);
 async function act(type:string,payload:Row){if(!state||busy)return;setBusy(true);try{const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,payload,expected_version:state.version,request_id:crypto.randomUUID()})});const d=await r.json() as {state?:Workspace;mode?:string;error?:string};if(!r.ok||!d.state||!d.mode)throw new Error(d.error||'The workspace response was incomplete.');setState(d.state);setModal(null);toast.success('Saved to '+(mode==='demo'?'your sample workspace':'Google Sheets'));}catch(e){toast.error(e instanceof Error?e.message:'Could not save. Your form is still open.');}finally{setBusy(false)}}
 const current=state?.leads.find(l=>l.lead_id===selected),today=day();
 const pending=state?.followups.filter(f=>f.followup_status==='Pending')||[],overdue=pending.filter(f=>f.followup_due_date&&f.followup_due_date<today),due=pending.filter(f=>f.followup_due_date===today),visits=state?.visits.filter(v=>v.visit_status==='Scheduled')||[];
 const nextDue=(id:string)=>pending.filter(f=>f.lead_id===id).map(f=>f.followup_due_date).filter(Boolean).sort()[0]||'';
 const intel=(id:string)=>state?.intelligence.find(i=>i.lead_id===id),lead=(id:string)=>state?.leads.find(l=>l.lead_id===id);
 const search=(r:Row)=>Object.values(r).some(v=>String(v).toLowerCase().includes(query.toLowerCase()));
 const followupRows=pending.filter(f=>view!=='followups'||(search(f)&&(filter==='All'||filter==='Overdue'&&f.followup_due_date<today||filter==='Due today'&&f.followup_due_date===today))).sort((a,b)=>String(a.followup_due_date).localeCompare(String(b.followup_due_date)));
 const openForm=(type:string,r:Row={})=>{setSelected(null);setModal({type,...r})};
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const p:any=Object.fromEntries(new FormData(e.currentTarget).entries());for(const key of ['lead_id','followup_id','site_visit_id','proposal_id','delivery_id'])if(modal?.[key])p[key]=modal[key];if(p.starts_at)p.starts_at=new Date(p.starts_at).toISOString();if(modal?.type==='revise_proposal'){p.operation='revise';await act('update_proposal',p);}else await act(modal!.type,p);}
 const followupTable=(rows:Row[])=>rows.length?<Table><TableHeader><TableRow><TableHead>Enquiry</TableHead><TableHead>Next action</TableHead><TableHead>Owner</TableHead><TableHead>Due</TableHead><TableHead/></TableRow></TableHeader><TableBody>{rows.map(f=><TableRow key={f.followup_id}><TableCell><button className="record-name" onClick={()=>setSelected(f.lead_id)}>{lead(f.lead_id)?.company_name||f.client_name}</button><small>{f.client_name}</small></TableCell><TableCell><span className="task-copy">{f.next_action}</span><small>{f.channel||'Manual'} · {f.followup_stage}</small></TableCell><TableCell>{f.assigned_to}</TableCell><TableCell><span className={f.followup_due_date<today?'due-over':''}>{date(f.followup_due_date)}</span><small>{f.followup_due_date<today?'Overdue':f.followup_due_date===today?'Today':'Upcoming'}</small></TableCell><TableCell><Button size="sm" variant="outline" disabled={busy} onClick={()=>openForm('complete_followup',f)}><Check size={15}/>Complete</Button></TableCell></TableRow>)}</TableBody></Table>:<Empty text="No pending follow-ups in this view."/>;
 return <SidebarProvider><Sidebar className="solar-sidebar"><SidebarHeader><div className="brand"><span className="brand-icon"><Sun/></span><div>Solar EPC<small>OPERATIONS</small></div></div></SidebarHeader><SidebarContent><SidebarGroup><p className="nav-caption">WORKSPACE</p><SidebarMenu>{nav.map(([key,label,Icon])=><SidebarMenuItem key={key}><SidebarMenuButton isActive={view===key} onClick={()=>{setView(key);setQuery('');setFilter('All')}}><Icon/><span>{label}</span>{key==='followups'&&pending.length>0&&<b className="nav-count">{pending.length}</b>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup></SidebarContent><SidebarFooter><div className="sidebar-note"><Sun size={18}/><p>From enquiry<br/><strong>to the next step.</strong></p></div><div className="owner"><span>AC</span><div>Arjun Choudhary<small>Portfolio workspace · V2</small></div></div></SidebarFooter></Sidebar><SidebarInset>
 <header className="topbar"><div><SidebarTrigger/><span>Solar EPC Operations Command Center</span></div><div className="top-actions"><span className="mode-label">{mode==='demo'?'Sample workspace':'Google Sheets'}</span><Button variant="ghost" size="icon" aria-label="Refresh workspace" onClick={load}><RefreshCw size={17}/></Button></div></header>
 <main className="workspace-main"><div className="page-heading"><div><p className="eyebrow">{new Date().toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long',timeZone:'Asia/Kolkata'})}</p><h1>{nav.find(n=>n[0]===view)?.[1]}</h1><p className="subtitle">{view==='overview'?'Keep every enquiry moving.':view==='followups'?'Complete the action. Record the outcome.':view==='visits'?'Plan the visit and capture what matters.':view==='proposals'?'Track every version through to a decision.':view==='setup'?'Connect your workflows when you are ready.':view==='activity'?'A record of the decisions and changes.':'Your solar pipeline, in one place.'}</p></div><Button className="primary-button" onClick={()=>openForm('create_lead')} disabled={!state}><Plus size={18}/>New enquiry</Button></div>
 {mode==='demo'&&<div className="demo-banner"><span>DEMO</span>Fictional enquiries. Practice changes are saved here; Google Sheets and client messages are not affected.</div>}
 {error?<div className="error-panel" role="alert"><AlertCircle/><p>{error}</p><Button onClick={load}>Try again</Button></div>:!state?<div className="loading-grid">{[1,2,3,4].map(i=><Skeleton key={i} className="h-32"/>)}</div>:<>
 {view==='overview'&&<><div className="metrics"><article><span>Open enquiries<Users size={17}/></span><strong>{state.leads.filter(l=>!isStopped(l)).length}</strong><small>{state.leads.length} enquiries captured</small></article><article className="attention"><span>Follow-ups overdue<Clock3 size={17}/></span><strong>{overdue.length}</strong><small>{due.length} more due today</small></article><article><span>Scheduled site visits<MapPin size={17}/></span><strong>{visits.length}</strong><small>{state.visits.filter(v=>v.visit_status==='Completed').length} completed visits</small></article><article><span>Proposals in progress<FileText size={17}/></span><strong>{state.proposals.filter(p=>!['Accepted','Declined'].includes(p.proposal_status)).length}</strong><small>{state.proposals.filter(p=>p.proposal_status==='Accepted').length} accepted proposals</small></article></div>
 <div className="overview-grid"><section className="panel"><div className="panel-heading"><div><h2>Next actions</h2><p>Start with the enquiries that need attention.</p></div><Button variant="ghost" onClick={()=>setView('followups')}>View all<ArrowUpRight size={16}/></Button></div>{followupTable(followupRows.slice(0,5))}</section><aside className="panel pipeline-panel"><div className="panel-heading"><h2>Pipeline snapshot</h2></div>{['Qualified','Contacted','Site Visit','Proposal','Converted'].map((status,i)=>{const n=state.leads.filter(l=>l.current_status===status).length;return <div className="pipeline-row" key={status}><div><span>{status}</span><strong>{n}</strong></div><div className="bar-track"><span style={{width:Math.max(3,n/Math.max(state.leads.length,1)*100)+'%',background:['#204b73','#44769d','#d99716','#7254a0','#238262'][i]}}/></div></div>})}<div className="pipeline-bottom"><span>Lead quality</span><div>{['Hot','Warm','Cold'].map(t=><div key={t}><Badge>{t}</Badge><strong>{state.intelligence.filter(i=>String(i.lead_temperature).toLowerCase()===t.toLowerCase()).length}</strong></div>)}</div></div></aside></div>
 <section className="panel visits-strip"><div className="panel-heading"><h2>Upcoming site work</h2><Button variant="ghost" onClick={()=>setView('visits')}>View visits<ArrowUpRight size={16}/></Button></div>{visits.length?<div className="visit-cards">{visits.slice(0,3).map(v=><button key={v.site_visit_id} onClick={()=>setSelected(v.lead_id)}><span className="calendar-tile"><CalendarDays/><strong>{date(v.visit_date)}</strong></span><span><strong>{lead(v.lead_id)?.company_name||v.client_name}</strong><small>{v.assigned_engineer} · {lead(v.lead_id)?.location}</small></span><ChevronRight/></button>)}</div>:<Empty text="No site visits scheduled yet."/>}</section></>}
 {view==='leads'&&<section className="panel"><div className="toolbar"><div className="search"><Search size={17}/><Input placeholder="Search company, client or location" value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search enquiries"/></div><Choice options={['All','Hot','Warm','Cold']} value={filter} onChange={setFilter} label="Filter by lead temperature"/></div><Table><TableHeader><TableRow><TableHead>Company / client</TableHead><TableHead>Project</TableHead><TableHead>Priority</TableHead><TableHead>Owner</TableHead><TableHead>Status</TableHead><TableHead>Next follow-up</TableHead></TableRow></TableHeader><TableBody>{state.leads.filter(l=>search(l)&&(filter==='All'||String(intel(l.lead_id)?.lead_temperature).toLowerCase()===filter.toLowerCase())).map(l=><TableRow key={l.lead_id}><TableCell><button className="record-name" onClick={()=>setSelected(l.lead_id)}>{l.company_name||l.client_name}</button><small>{l.client_name} · {l.location}</small></TableCell><TableCell>{l.project_type}<small>{l.estimated_capacity}</small></TableCell><TableCell><Badge>{intel(l.lead_id)?.lead_temperature}</Badge></TableCell><TableCell>{l.assigned_to}</TableCell><TableCell><Badge>{l.manual_stop==='Yes'?'Stopped':l.current_status}</Badge></TableCell><TableCell>{date(nextDue(l.lead_id))}</TableCell></TableRow>)}</TableBody></Table></section>}
 {view==='followups'&&<section className="panel"><div className="toolbar"><div className="search"><Search size={17}/><Input placeholder="Search follow-ups" value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search follow-ups"/></div><Choice options={['All','Overdue','Due today']} value={filter} onChange={setFilter} label="Follow-up deadline"/></div>{followupTable(followupRows)}</section>}
 {view==='visits'&&<section className="panel"><div className="panel-heading"><h2>Site visit tracker</h2><p>Schedule a visit from any enquiry.</p></div>{state.visits.length?<Table><TableHeader><TableRow><TableHead>Enquiry</TableHead><TableHead>Engineer</TableHead><TableHead>Visit</TableHead><TableHead>Status</TableHead><TableHead>Calendar</TableHead><TableHead/></TableRow></TableHeader><TableBody>{state.visits.map(v=><TableRow key={v.site_visit_id}><TableCell><button className="record-name" onClick={()=>setSelected(v.lead_id)}>{lead(v.lead_id)?.company_name||v.client_name}</button><small>{v.required_documents||'No documents specified'}</small></TableCell><TableCell>{v.assigned_engineer}</TableCell><TableCell>{date(v.visit_date)}<small>{v.starts_at&&new Date(v.starts_at).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Kolkata'})} IST</small></TableCell><TableCell><Badge>{v.visit_status}</Badge></TableCell><TableCell><Badge>{v.calendar_sync_status||'Pending'}</Badge></TableCell><TableCell><Button size="sm" variant="outline" onClick={()=>openForm('update_visit',v)}>Update visit</Button></TableCell></TableRow>)}</TableBody></Table>:<Empty text="Open an enquiry to schedule the first site visit."/>}</section>}
 {view==='proposals'&&<section className="panel"><div className="panel-heading"><h2>Proposal tracker</h2><p>Documents are generated by the connected workflow.</p></div>{state.proposals.length?<Table><TableHeader><TableRow><TableHead>Enquiry</TableHead><TableHead>Amount</TableHead><TableHead>Version</TableHead><TableHead>Status</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader><TableBody>{state.proposals.map(p=><TableRow key={p.proposal_id}><TableCell><button className="record-name" onClick={()=>setSelected(p.lead_id)}>{lead(p.lead_id)?.company_name||p.client_name}</button><small>Document: {p.document_status}</small></TableCell><TableCell>{money(p.amount)}</TableCell><TableCell>v{p.proposal_version}</TableCell><TableCell><Badge>{p.proposal_status}</Badge></TableCell><TableCell><div className="row-actions"><Button size="sm" variant="outline" onClick={()=>openForm('revise_proposal',p)} disabled={['Accepted','Declined'].includes(p.proposal_status)}>Revise</Button>{p.proposal_status==='Draft'&&<Button size="sm" disabled={busy||p.document_status!=='Ready'} onClick={()=>act('update_proposal',{proposal_id:p.proposal_id,operation:'share'})}>Share</Button>}{p.proposal_status==='Shared'&&<><Button size="sm" disabled={busy} onClick={()=>act('update_proposal',{proposal_id:p.proposal_id,operation:'accept'})}>Accept</Button><Button size="sm" variant="outline" disabled={busy} onClick={()=>act('update_proposal',{proposal_id:p.proposal_id,operation:'decline'})}>Decline</Button></>}{p.document_url&&<a className="text-link" href={p.document_url} target="_blank" rel="noreferrer">Open draft</a>}</div></TableCell></TableRow>)}</TableBody></Table>:<Empty text="Open an enquiry to create a proposal draft."/>}</section>}
 {view==='activity'&&<section className="panel"><div className="panel-heading"><h2>Activity log</h2><span>{state.activity.length} events</span></div><div className="activity-list">{[...state.activity].reverse().slice(0,80).map(a=><article key={a.event_id}><span className="activity-icon"><Activity size={16}/></span><div><strong>{String(a.action).replaceAll('_',' ')}</strong><p>{lead(a.lead_id)?.company_name||'Workspace'} · {a.actor}</p></div><time>{date(a.created_at)} · {new Date(a.created_at).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Kolkata'})}</time></article>)}</div></section>}
 {view==='setup'&&<><div className="connection-grid"><section className="panel connection-card"><span className="connection-icon"><Settings2/></span><h2>{mode==='demo'?'Connect your Solar Sheet':'Google Sheets connected'}</h2><p>{mode==='demo'?'Deploy the included Apps Script bridge, then add its URL and token to the site’s server settings.':'Changes in this workspace are saved through the Solar API to your Google Sheet.'}</p><ol><li>Download the connection package.</li><li>Deploy the Apps Script files using the guide.</li><li>Import the six n8n workflows and connect credentials.</li><li>Test with your own inbox and test calendar.</li></ol><a className="download-button" href="/downloads/solar-v2-package.zip"><Download size={18}/>Download workflows and setup guide</a></section><section className="panel connection-card"><h2>Delivery controls</h2><div className="connection-stat"><span>Data source</span><Badge>{mode==='demo'?'Sample data':'Google Sheets'}</Badge></div><div className="connection-stat"><span>Automation</span><Badge>{state.config.AUTOMATION_ENABLED==='Yes'?'Enabled':'Paused'}</Badge></div><div className="connection-stat"><span>Sending mode</span><Badge>{state.config.SEND_MODE}</Badge></div><p>Set recipients and enable automation in the <strong>V2_Config</strong> tab after connection tests. Legacy follow-ups start with automation off.</p><a className="text-link" href="https://docs.google.com/spreadsheets/d/17mExQ2XRc9me6NvG3ZpNjbnDOUt-ePt0FcicME_RFWY/edit#gid=2096001001" target="_blank" rel="noreferrer">Open Solar configuration <ArrowUpRight size={15}/></a></section></div><section className="panel"><div className="panel-heading"><h2>Delivery queue</h2><p>Verify uncertain outcomes before retrying.</p></div><Table><TableHeader><TableRow><TableHead>Type</TableHead><TableHead>Enquiry</TableHead><TableHead>Status</TableHead><TableHead>Detail</TableHead><TableHead/></TableRow></TableHeader><TableBody>{[...state.deliveries].reverse().slice(0,30).map(d=><TableRow key={d.delivery_id}><TableCell>{d.kind}</TableCell><TableCell>{lead(d.lead_id)?.company_name||'Manager summary'}</TableCell><TableCell><Badge>{d.status}</Badge></TableCell><TableCell>{d.error_message||(d.status==='Sent'?'Delivery confirmed':d.status==='Cancelled'?'Delivery cancelled':'Waiting for the connected worker')}</TableCell><TableCell>{d.status==='Needs review'&&<Button size="sm" variant="outline" onClick={()=>openForm('reconcile_delivery',d)}>Review</Button>}</TableCell></TableRow>)}</TableBody></Table></section></>}
 </>}
 <footer className="workspace-footer"><span>Solar EPC · Portfolio project by Arjun Choudhary</span><span>Operational dates use IST</span></footer></main>
 <Sheet open={!!current} onOpenChange={open=>!open&&setSelected(null)}><SheetContent className="detail-sheet"><SheetHeader><SheetDescription>ENQUIRY DETAILS</SheetDescription><SheetTitle>{current?.company_name||current?.client_name}</SheetTitle></SheetHeader>{current&&<div className="detail-body"><div className="detail-badges"><Badge>{current.current_status}</Badge><Badge>{intel(current.lead_id)?.lead_temperature}</Badge></div><h3>{current.client_name}</h3><p>{current.email}<br/>{current.phone||'Phone not provided'}</p><dl>{[['Location',current.location],['Project',current.project_type],['Capacity',current.estimated_capacity],['Budget',current.budget_range],['Timeline',current.timeline],['Owner',current.assigned_to],['Next follow-up',date(nextDue(current.lead_id))]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v||'To confirm'}</dd></div>)}</dl><div className="insight"><h3>Next conversation</h3><p>{intel(current.lead_id)?.suggested_next_action}</p><small>Missing information: {intel(current.lead_id)?.missing_information||'None recorded'}</small></div><p>{current.message}</p><div className="detail-buttons"><Button onClick={()=>openForm('add_followup',current)} disabled={isStopped(current)}>Add follow-up</Button><Button variant="outline" onClick={()=>openForm('schedule_visit',current)} disabled={isStopped(current)}>Schedule visit</Button><Button variant="outline" onClick={()=>openForm('create_proposal',current)} disabled={isStopped(current)}>Create proposal</Button><Button variant="outline" onClick={()=>openForm('update_lead',current)}>Edit owner / status</Button><Button variant="ghost" disabled={busy} onClick={()=>act('update_lead',{lead_id:current.lead_id,manual_stop:current.manual_stop==='Yes'?'No':'Yes'})}>{current.manual_stop==='Yes'?<Play size={16}/>:<PauseCircle size={16}/>} {current.manual_stop==='Yes'?'Remove manual stop':'Stop automation'}</Button></div></div>}</SheetContent></Sheet>
 <Dialog open={!!modal} onOpenChange={open=>!open&&!busy&&setModal(null)}><DialogContent className="action-dialog"><DialogHeader><DialogTitle>{({create_lead:'New enquiry',add_followup:'Plan a follow-up',complete_followup:'Complete follow-up',schedule_visit:'Schedule site visit',update_visit:'Update site visit',create_proposal:'Create proposal draft',revise_proposal:'Revise proposal',update_lead:'Update enquiry',reconcile_delivery:'Verify delivery outcome'} as Row)[modal?.type||'']}</DialogTitle><DialogDescription>{modal?.client_name||'Keep the next action clear and traceable.'}</DialogDescription></DialogHeader>{modal&&state&&<form onSubmit={submit} className="action-form" key={modal.type+(modal.lead_id||'')}>
 {modal.type==='create_lead'&&<><div className="form-grid"><Field name="client_name" label="Client name" required/><Field name="company_name" label="Company / property"/><Field name="email" label="Email" type="email" required/><Field name="phone" label="Phone"/><Field name="location" label="Location" required/><label className="field"><span>Project type</span><Choice name="project_type" options={['Residential','Commercial','Industrial','Institutional']}/></label><Field name="estimated_capacity" label="Estimated capacity"/><Field name="budget_range" label="Budget range"/><label className="field"><span>Timeline</span><Choice name="timeline" options={['Within 1 month','Immediately','1-3 months','3-6 months','Just exploring']}/></label><label className="field"><span>Site visit required</span><Choice name="site_visit_required" options={['Yes','No']}/></label></div><label className="field"><span>Requirement</span><Textarea name="message"/></label></>}
 {modal.type==='update_lead'&&<><label className="field"><span>Owner</span><Choice name="assigned_to" options={state.team.filter(t=>t.active_status==='Active').map(t=>t.team_member)} value={modal.assigned_to}/></label><label className="field"><span>Status</span><Choice name="current_status" options={['Qualified','Contacted','Site Visit','Proposal','Converted','Lost','Stopped']} value={['Qualified','Contacted','Site Visit','Proposal','Converted','Lost','Stopped'].includes(modal.current_status)?modal.current_status:'Qualified'}/></label><label className="field"><span>Notes</span><Textarea name="notes" defaultValue={modal.notes}/></label></>}
 {modal.type==='add_followup'&&<><Field name="due_date" label="Due date (IST)" type="date" value={addDays(today,1)} required/><Field name="next_action" label="Next action" required/><label className="field"><span>Channel</span><Choice name="channel" options={['Manual','Email']}/></label><label className="field"><span>Allow automated email for this task</span><Choice name="automation_enabled" options={['No','Yes']}/></label></>}
 {modal.type==='complete_followup'&&<><label className="field"><span>Outcome</span><Choice name="outcome" options={['Contacted','No answer','Details received','Visit requested','Awaiting response']}/></label><label className="field"><span>Notes</span><Textarea name="notes"/></label><Field name="next_due_date" label="Next follow-up date (optional)" type="date"/></>}
 {modal.type==='schedule_visit'&&<><Field name="starts_at" label="Visit time (your local timezone)" type="datetime-local" required/><label className="field"><span>Assigned engineer</span><Choice name="assigned_engineer" options={state.team.filter(t=>t.active_status==='Active').map(t=>t.team_member)} value={state.team.find(t=>t.role==='Site Engineer')?.team_member}/></label><Field name="required_documents" label="Documents to collect"/></>}
 {modal.type==='update_visit'&&<><label className="field"><span>Visit status</span><Choice name="visit_status" options={['Scheduled','Completed','Cancelled']} value={modal.visit_status}/></label><Field name="starts_at" label="New visit time (optional, local timezone)" type="datetime-local"/><label className="field"><span>Visit findings</span><Textarea name="visit_notes" defaultValue={modal.visit_notes}/></label><Field name="photos_link" label="Photos folder link (HTTPS)" value={modal.photos_link}/><Field name="required_documents" label="Documents" value={modal.required_documents}/></>}
 {['create_proposal','revise_proposal'].includes(modal.type)&&<><Field name="amount" label="Proposal amount (INR)" type="number" value={modal.amount||''} required/><label className="field"><span>Scope and bill of quantities</span><Textarea name="notes" rows={6} required defaultValue={modal.notes}/></label><p className="form-hint">Saving queues a draft document. Review it before sharing with the client.</p></>}
 {modal.type==='reconcile_delivery'&&<><p>Check the provider before recording an outcome. Retry only when the action did not complete.</p><label className="field"><span>Resolution</span><Choice name="resolution" options={['retry','sent']}/></label><Field name="provider_id" label="Provider ID (required for sent)"/><Field name="document_url" label="Document URL (document deliveries only)"/><Field name="pdf_url" label="PDF URL (document deliveries only)"/><Field name="note" label="What did you verify?" required/></>}
 <div className="form-actions"><Button type="button" variant="outline" disabled={busy} onClick={()=>setModal(null)}>Cancel</Button><Button className="primary-button" type="submit" disabled={busy}>{busy?'Saving…':'Save'}</Button></div></form>}</DialogContent></Dialog><Toaster richColors/></SidebarInset></SidebarProvider>;
}
